#!/bin/zsh

# Config
alias reload="source $HOME/.zshrc"
alias dotfiles="code $HOME/.local/share/chezmoi"

# Navigation
alias cd="z"

# Python
alias python='python3'
alias pip='pip3'


# Eza
alias ld='eza -lD'  # lists only directories (no files)
alias lf='eza -lfh'  # lists only files (no directories) with column headers
alias lh='eza -dl .* --group-directories-first'  # lists hidden files and directories
alias ls='eza -alh --group-directories-first'  # lists everything with directories first with column headers

alias cat="bat"

# alias sshnuc="ssh root@192.168.1.52"
# alias acm="asciinema"

# Git
alias lg='lazygit'

