#!/bin/zsh

# Config
alias reload="source $HOME/.zshrc"
# alias dotfiles="code ~/dotfiles"

# Navigation
alias cd="z"

# Python
alias python='python3'
alias pip='pip3'


# Eza
alias ls='eza'
alias ll='eza -lh'
alias l='eza -lah'

alias cat="bat"

# alias sshnuc="ssh root@192.168.1.52"
# alias acm="asciinema"

# Git
alias lg='lazygit'

