#!/usr/bin/env python3
import os

print("--- Starting dotfiles bootstrap ---\n")

ignored = [".git", "manual"]
folders = []
for file in os.listdir("."):
    if os.path.isdir(os.path.abspath(file)) and file not in ignored:
        folders.append(file)

for folder in folders:
    os.system(f"./{folder}/setup")
    print()
