#!/bin/zsh

# Config
alias reload="source $HOME/.zshrc"
alias dotfiles="code ~/dotfiles"

# Listing
alias ll='ls -l'
alias la='ls -la'

# Navigation
alias ..='cd ..'
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Python
alias python='python3'
alias pip='pip3'

# Misc
alias cat="bat"